### PR TITLE
[Don't merge]Test funcunit with steal_qunit1

### PR DESCRIPTION
**Pull request by shayaneumar**

### CODE REVIEW

**Comment by shayaneumar** [comment]
@matthewp  Fun Unit is breaking with the new steal_qunit1 that you have published. 
What am I doing wrong here? I have replaced all the references of steal_qunit to steal_qunit1

**Comment by shayaneumar** [comment]
@matthewp 

I have created a fork of steal_quint and named it as steal_qunit2, with that all the tests are passing.
https://github.com/bitovi/funcunit/pull/205/files

Issue with steal_qunit1 needs to be addressed before I can proceed, I am not able to figure out why steal_qunit1 does not work.

**Comment by shayaneumar** [comment]
@matthewp need ur input on this.

**Comment by matthewp** [comment]
I'm not able to dedicate time to debugging FuncUnit, sorry. But the qunit2 approach sounds fine to me.

**Pull request closed without merging**
