### PR TITLE
Mocha: Allow tests to continue to run after a fail

### PR DESCRIPTION
**Pull request by matthewp**
In Mocha an error results in an exception getting thrown. Since this
exception was never caught there would always be the error item in the
queue that would prevent the next test from completing. The fix is to
make sure that we mark the test as done so that the next queued item can
be ran.

### CODE REVIEW

**Comment by daffl** [comment]
Any reason why this never go merged?

**Comment by matthewp** [comment]
I don't think it's the correct solution to the problem. I was never able to confirm that this was why the tests would get stuck.

**Comment by daffl** [comment]
Should we close this one then? I haven't seen the tests get stuck in Mocha for a while?

**Comment by matthewp** [comment]
Sure

**Pull request closed without merging**
